title: Botswana Technology Blog
author: Lefika M
email: lmmelesi@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  All technology news summaries, opportunities around the world with special emphasis
  on those applicable to Batswana.

# social links
twitter_username: @novammelesi
github_username:  fikstoday

show_excerpts: true # set to false to remove excerpts on the homepage
theme:minima
